rangefilter/filter/urls.py
from django.conf.urls import url 
from .views import apartfilter

urlpatterns = [
	url(r'^$', apartfilter, name='browse-apartment'),
	
	]

rangefilter/rangefilter/urls.py
from django.conf.urls import url,include
from django.contrib import admin
from django.conf import settings
from django.conf.urls.static import static

urlpatterns = [
    url(r'^admin/', admin.site.urls),
    url(r'^', include('filter.urls', namespace = 'browse')), 
]



if settings.DEBUG:
    urlpatterns += static(settings.MEDIA_URL, document_root=settings.MEDIA_ROOT)

rangefilter/filter/models.py
from __future__ import unicode_literals
from django.contrib.auth.models import User
from django.db import models

""" 
This is an example of a  model for slider range filter 

"""

class City(models.Model):
    name = models.CharField(max_length = 80)

    def __str__(self):
        return self.name



class Apartment(models.Model):
    TYPE = (
        ('House', 'House'),
        ('Apartment','Apartment'),
    )
    BATHROOM =(
        ('Shared','Shared'),
        ('Private','Private'),

    )
    WATER_SUPPLY=(
        ('Limited','Limited'),
        ('24hrs Supply','24hrs Supply')
    )
    FURNISHED=(
        ('Well-Furnished','Well-Furnished'),
        ('Semi-Furnished','Semi-Furnished'),
        ('None','None'),
    )
    MINIMUM_STAY=(
        ('3 Months','3 Months'),
        ('6 Months','6 Months'),
        ('12 Months','12 Months'),
        ('More','More'),
    )
    UTILITIES_COST=(
        ('Included','Included'),
        ('Excluded','Excluded'),
    )
    MAX_OCCUPENCY=(
        ('Two','2'),
        ('Three','3'),
        ('Four','4'),
        ('Five','5'),
    )
    KITCHEN=(
        ('Private','Private'),
        ('Shared','Shared'),
    )
    user = models.ForeignKey(User, blank = True, null = True)
    city = models.ForeignKey(City, blank = True, null = True)
    apartment_type = models.CharField(max_length=100, choices = TYPE)
    location=models.CharField(max_length=100)
    description=models.TextField()
    internet=models.BooleanField(default=False)
    area=models.CharField(max_length=100)
    bedroom=models.PositiveIntegerField()
    bathroom=models.CharField(max_length=100, choices = BATHROOM) 
    water_supply=models.CharField(max_length=100, choices = WATER_SUPPLY)
    furnished=models.CharField(max_length=100, choices = FURNISHED)
    mininun_stay=models.CharField(max_length=100, choices = MINIMUM_STAY)
    utilities_cost=models.CharField(max_length=100, choices = UTILITIES_COST)
    parking=models.BooleanField(default=False)
    rent=models.PositiveIntegerField()
    max_occupency=models.CharField(max_length=100, choices = MAX_OCCUPENCY)
    apartment_avaibility=models.BooleanField(default=False)
    kitchen=models.CharField(max_length=100, choices = KITCHEN)
    favorites = models.PositiveIntegerField(default=0, null=True, blank= True)

    def __str__(self):
        return 'Apartment Type: {}, Apartment Location : {}'.format(self.apartment_type,self.location)

    



class ApartmentImage(models.Model):
    
    apartment = models.ForeignKey(Apartment)
    apartment_image=models.ImageField(upload_to='media/apartment_image', null=True)
    

rangefilter/filter/views.py
from django.shortcuts import render
from .models import Apartment 
from .filters import ApartmentFilter

# Views for filtering the list of apartments
def apartfilter(request):
	apartment_list = Apartment.objects.all()
	apartment_filter = ApartmentFilter(request.GET, queryset=apartment_list)
	return render(request, 'apartmentapp_filter.html',{'filter':apartment_filter})

rangefilter/filter/templates/apartmentapp_filter.html
{% load staticfiles %}
{% include 'head.html' %}
{% load widget_tweaks %}
<main>               
<section class="listing-wrap">
  <div class="container">
    <div class="row">
      <div class="col-sm-3">
        <div class="filter-results">
          <div class="title">
            <h4>Search the results</h4>
          </div>
          <div class="content">
            <form method="get">
              <div class="form-group">
                {{ filter.form.apartment_type.label_tag }}
                {% render_field filter.form.apartment_type class="form-control" %}
              </div>
              <div class="form-group">
                {{ filter.form.location.label_tag }}
                {% render_field filter.form.location class="form-control" %}
              </div>
              
              <div class="form-group">

                {{ filter.form.internet.label_tag }}
                {% render_field filter.form.internet class="form-control" %}
              </div>

<!--  Jquery ( Needed for the Range Slider  filter) -->
<link rel="stylesheet" href="{% static 'css/jquery-ui.css.css' %}">
  <link rel="stylesheet" href="/resources/demos/style.css">
  <script src="https://code.jquery.com/jquery-1.12.4.js"></script>
  <script src="https://code.jquery.com/ui/1.12.1/jquery-ui.js"></script>
  <script>
  // scripts for the range slider 
   $(document).ready(function () {
      var outputSpan = $('#spanOutput');
      var sliderDiv = $('#slider');

      sliderDiv.slider({
          range: true,
          min: 0,
          max: 10000,
          values: [0, 10000],
          slide: function (event, ui) {
              outputSpan.html(ui.values[0] + ' $' + ' - ' + ui.values[1] + ' $');
          },
          stop: function (event, ui) {
              $('#MinRent').val(ui.values[0]);
              $('#MaxRent').val(ui.values[1]);
          }
      });

      outputSpan.html(sliderDiv.slider('values', 0) + ' $' + ' - '
          + sliderDiv.slider('values', 1) + ' $');
      $('#MinRent').val(sliderDiv.slider('values', 0));
      $('#MaxRent').val(sliderDiv.slider('values', 1));
  });
  </script>
  <!-- script end for range slider filter -->


<body style="font-family:Arial;">
<form id="formal" runat="server">
Rent : <span id="spanOutput"></span>
<br><br>
<div id="slider"  ></div>
<br>
<div class="form-group" >
<input  name="rent__gt" step="any" id="MinRent" class="form-control" type="hidden">
</div>
<div class="form-group" >
<input  name="rent__lt" step="any" id="MaxRent" class="form-control" type="hidden">
</div>
</body>
<br><br>
<button type="submit" class="btn-hover-left"><span>Submit</span></button>
</form>         
</div>
</div>

<!-- for the list of apartments -->
</div><!-- /.col-sm-3 -->
      <div class="col-sm-9">
        <div class="apartment-list">
          <h2>Available Apartments</h2>
          <div class="pagination-wrap clearfix">  
          
                </div>                        
          <div class="row">
          {% for filter in filter.qs %}
            <div class="col-sm-6 col-md-4" ">
              <div class="apartment" >
                <div class="item">
                  <div class="top">
                    <a href="#">
                    {% for image in filter.apartmentimage_set.all %}
                      {% if forloop.first %}

                    <img src="{{ image.apartment_image.url }}" alt="">
                    {% endif %}
                        {% endfor %}
                    </a>
                  </div>
                    
                  <div class="bottom">
                    <h3 class="address"><a href="#">{{ filter.location |upper }}</a></h3>
                    <h5>{{ filter.area }} sq feet</h5>
                    
                  </div>
                  <div class="price">
                    <h4><a href="#">${{ filter.rent }}</a></h4>
                  </div>
                </div>
              </div>
              
            </div>
           {% empty %}
        
          <h1 style="text-align: center;">No data</h1>
        {% endfor %}
        </div>               
      </div>
    </div>
  </div> 
  </div>
</section>
</main>
<!-- footer section -->

<!-- end footer section -->
</body>
</html>

rangefilter/filter/templates/head.html
{% load staticfiles %}
<!DOCTYPE html>
<html lang="en">
<head>
<meta charset="utf-8">
<meta http-equiv="X-UA-Compatible" content="IE=edge">
<meta name="viewport" content="width=device-width, initial-scale=1">
<title>Apartment</title>
<!--fonts-->
<!--/.fonts-->

<!-- Stylesheets -->
<link href="{% static 'css/bootstrap.min.css' %}" rel="stylesheet">
<link href="{% static 'css/font-awesome.min.css' %}" rel="stylesheet">
<link rel="stylesheet" href="{% static 'fonts/fonts.css' %}">
<link href="{% static 'css/slick.css' %}" rel="stylesheet">
<link href="{% static 'css/slick-theme.css' %}" rel="stylesheet">
<link href="{% static 'css/style.css' %}" rel="stylesheet">
<link href="{% static 'css/responsive.css' %}" rel="stylesheet">


<!-- jQuery (necessary for Bootstrap's JavaScript plugins) -->
<script src="{% static 'js/jquery.min.js' %}"></script>
<!-- <script src = "https:/ajax.googleapis.com/ajax/libs/jquery/1.11.3/jquery.min.js"></script> -->
<!-- Include all compiled plugins (below), or include individual files as needed -->
<script src="{% static 'js/bootstrap.min.js' %}"></script>
<script src="{% static 'js/jquery.typeahead.bundle.js' %}"></script>
<script src="{% static 'js/search.typehead.js' %}"></script>

<script src="{% static 'js/slick.min.js' %}"></script>
<script src="{% static 'js/masonry.pkgd.min.js' %}"></script>
<script src="{% static 'js/script.js' %}"></script>

</head>